### ISSUE TITLE
showInputBox?

### ISSUE THREAD

**Issue by abasse** [philippthiele/Voop#10]
Hi, how can I create a custom voop script with an InputBox to prompt the user for further details, before the output is written to the doc?

This does not work for me:

`const vscode = require('vscode');

 function main(input) {

	const tagName = '';

    askForName().then(name => {
        if (!name) {
            return;
        }
        tagName = name;
        input.insert(tagName);
    });

}

async function askForName() {
    const compName = await vscode.window.showInputBox({ placeHolder: 'Name of the component' });
    if (compName === undefined) {
        return false;
    }
    return compName;
}
`

**Comment by philippthiele** [comment]
Hi @abasse ,

see the "userInput" documentation: https://github.com/philippthiele/Voop/blob/main/CustomScriptDevelopment.md
An example voop script using it: https://github.com/philippthiele/Voop/blob/main/scripts/JoinLines.js
If you set "userInput" to true in the metadata, it will automatically ask the user for an input.

**Comment by abasse** [comment]
Thanks!
