### ISSUE TITLE
http request from custom script

### ISSUE THREAD

**Issue by abasse** [philippthiele/Voop#6]
I was wondering, if it is possible to do a http request from a custom script and to return the result via "input.insert()".

**Comment by philippthiele** [comment]
Yes, you can do that, e.g. with plain nodejs http requests:

```
/**
	{
		"api":1,
		"name":"Test HTTP Request",
		"description":"",
		"author":"philippthiele",
		"icon":"collapse",
		"tags":"test"
	}
**/

const https = require('https');

function main(input) {
	return new Promise((resolve) => {
		const options = {
			hostname: 'google.com',
			port: 443,
			path: '',
			method: 'GET',
		};
		
		const req = https.request(options, res => {
			input.insert(`statusCode: ${res.statusCode}\n`);
		
			res.on('data', d => {
				input.insert(d);
			});

			res.on('end', function () { 
				resolve();
			});
		});
		
		req.on('error', error => {
			input.insert(error);
			resolve();
		});
		
		req.end();

		input.insert("request was send\n");
	})
}
```

**Comment by philippthiele** [comment]
result of getting from google via the script above:
![image](https://user-images.githubusercontent.com/1737722/190668785-dd4d976f-5230-4529-b2a8-c3bb4e4f566d.png)

**Comment by abasse** [comment]
Thanks so much for this example!

**Comment by philippthiele** [comment]
For future reference by others:
This exact problem is now also an example in the async operations documentation for custom scripts - https://github.com/philippthiele/Voop/blob/main/CustomScriptDevelopment.md#usage-of-promises-for-async-operations
