### ISSUE TITLE
Require of node_modules not supported in custom scripts folder

### ISSUE THREAD

**Issue by ShantanuVichare** [philippthiele/Voop#7]
I was working on a custom script which uses `axios` for making a network request.
I realized we cannot import node modules due to the misconfiguration of the necessary Module paths.

Having tested this, the fix is pretty simple:
In `extension.js`, the requireFromString expects the full file path. Thus replacing `selectedScript.scriptFileName` with `selectedScript.scriptPath`
```suggestion
      const voopScript = requireFromString(
        script + '\n\nfunction debug(input) {\n\tdebugger;\n\tmain(input);\n}\n\nmodule.exports = { "main": main, "debug": debug }',
        selectedScript.scriptPath
      );
```
This helps in resolving the Module paths properly and we can use npm packages in our custom scripts.

**Comment by philippthiele** [comment]
Thanks for the input! included it in the newest version of Voop.

**Comment by ShantanuVichare** [comment]
Thanks for your quick resolution. Really appreciate it. 🙏🏼
